FROM php:7.1-fpm

ENV TZ="/usr/share/zoneinfo/Europe/London"

RUN apt-get update && apt-get install -y git unzip zlib1g-dev

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install pdo pdo_mysql zip opcache

COPY shared/php.ini /usr/local/etc/php/php.ini
COPY dev/php.ini /usr/local/etc/php/php.ini.dev
RUN cd /usr/local/etc/php && cat php.ini.dev >> php.ini

RUN pecl install -o -f xdebug && docker-php-ext-enable xdebug
COPY dev/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

WORKDIR /var/www/istsi
