FROM php:7.1-fpm

ENV TZ="/usr/share/zoneinfo/Europe/London"

RUN apt-get update && apt-get install -y git unzip zlib1g-dev

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install pdo pdo_mysql zip opcache

COPY shared/php.ini /usr/local/etc/php/php.ini
COPY staging/php.ini /usr/local/etc/php/php.ini.staging
RUN cd /usr/local/etc/php && cat php.ini.staging >> php.ini && rm php.ini.staging

WORKDIR /var/www/istsi
