FROM php:7.1-fpm

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install pdo pdo_mysql

COPY shared/php.ini /usr/local/etc/php/php.ini
COPY staging/php.ini /usr/local/etc/php/php.ini.staging
RUN cd /usr/local/etc/php && cat php.ini.staging >> php.ini && rm php.ini.staging

WORKDIR /var/www/istsi
