FROM nginx

RUN usermod -u 1000 www-data

COPY shared/nginx.conf /etc/nginx/
COPY prod/istsi.conf /etc/nginx/conf.d/istsi.conf
RUN rm /etc/nginx/conf.d/default.conf

COPY shared/tls/istsi.pem /etc/nginx/ssl/istsi.pem
COPY shared/tls/istsi.key /etc/nginx/ssl/istsi.key
COPY shared/tls/cloudflare-origin-pulls.pem /etc/nginx/ssl/cloudflare-origin-pulls.pem

CMD ["nginx"]
