#!/bin/bash

psql -d $POSTGRES_DB -U $POSTGRES_USER <<-EOSQL
    CREATE USER "$POSTGRES_APP_USER" WITH PASSWORD '$POSTGRES_APP_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_APP_USER";
EOSQL
