FROM debian:jessie

RUN apt update && apt install -y nginx

COPY shared/nginx.conf /etc/nginx/
COPY staging/istsi.conf /etc/nginx/sites-available/

COPY shared/tls/istsi.pem /etc/nginx/ssl/istsi.pem
COPY shared/tls/istsi.key /etc/nginx/ssl/istsi.key

RUN ln -s /etc/nginx/sites-available/istsi.conf /etc/nginx/sites-enabled/istsi
RUN rm /etc/nginx/sites-enabled/default

RUN usermod -u 1000 www-data

CMD ["nginx"]

EXPOSE 443
