version: '3'

services:
    # mysql:
    #     image: mysql
    #     volumes:
    #         - data-mysql:/var/lib/mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    #         MYSQL_DATABASE: ${DB_NAME}
    #         MYSQL_USER: ${DB_APP_USER}
    #         MYSQL_PASSWORD: ${DB_APP_PASSWORD}
    #     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #     security_opt:
    #         - no-new-privileges
    postgres:
        build: postgres
        volumes:
            - data-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_APP_USER: ${DB_APP_USER}
            POSTGRES_APP_PASSWORD: ${DB_APP_PASSWORD}
            POSTGRES_INITDB_ARGS: --data-checksums
        security_opt:
            - no-new-privileges
    php:
        build:
            context: php
            dockerfile: Dockerfile.prod
            args:
                env: ${ENV}
        volumes:
            - ../app:/var/www/istsi:ro
            - data-app:/var/www/data
            - data-app-log:/var/www/logs
        security_opt:
            - no-new-privileges
    composer:
        build: composer
        user: www-data
        command: install --no-dev -o
        volumes:
            - ../app:/var/www/istsi
        security_opt:
            - no-new-privileges
    nginx:
        build:
            context: nginx
            args:
                SERVER_NAME: istsi.org
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../app/public:/var/www/istsi/public:ro
        security_opt:
            - no-new-privileges
    # backup-mysql:
    #     build: backup-mysql
    #     environment:
    #         MYSQL_HOST: mysql
    #         MYSQL_USER: ${DB_APP_USER}
    #         MYSQL_PASSWORD: ${DB_APP_PASSWORD}
    #         BACKUP_ON_INIT: 1
    #     volumes:
    #         - ../backups/mysql:/backup
    #     security_opt:
    #         - no-new-privileges
    backup-postgres:
        build: backup-postgres
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_APP_USER}
            POSTGRES_PASSWORD: ${DB_APP_PASSWORD}
            BACKUP_ON_INIT: 1
        volumes:
            - ../backups/postgres:/backup
        security_opt:
            - no-new-privileges
    backup-php:
        build: backup-php
        environment:
            PATH_TO_BACKUP: /data
            BACKUP_ON_INIT: 1
        volumes:
            - ../backups/php:/backup
            - data-app:/data
        security_opt:
            - no-new-privileges

volumes:
    # data-mysql:
    #     driver: local
    data-postgres:
        driver: local
    data-app:
        driver: local
    data-app-log:
        driver: local