version: '3'

services:
    mysql:
        image: mysql
        volumes:
            - data-mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        security_opt:
            - no-new-privileges
    php:
        build:
            context: php
            dockerfile: Dockerfile.prod
            args:
                env: ${ENV}
        volumes:
            - ../app:/var/www/istsi:ro
            - data-app:/var/www/data
            - data-app-log:/var/www/logs
        security_opt:
            - no-new-privileges
    composer:
        build: composer
        user: www-data
        command: install --no-dev -o
        volumes:
            - ../app:/var/www/istsi
        security_opt:
            - no-new-privileges
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile.prod
            args:
                env: ${ENV}
        ports:
            - 443:443
        volumes:
            - ../app/public:/var/www/istsi/public:ro
        security_opt:
            - no-new-privileges
    backup-mysql:
        build: backup-mysql
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            BACKUP_ON_INIT: 1
        volumes:
            - ../backups/mysql:/backup
        security_opt:
            - no-new-privileges
    backup-php:
        build: backup-php
        environment:
            PATH_TO_BACKUP: /data
            BACKUP_ON_INIT: 1
        volumes:
            - ../backups/php:/backup
            - data-app:/data
        security_opt:
            - no-new-privileges

volumes:
    data-mysql:
        driver: local
    data-app:
        driver: local
    data-app-log:
        driver: local