version: '3'

services:
    mysql:
        image: mysql
        volumes:
            - data-mysql:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    php:
        build:
            context: php
            dockerfile: Dockerfile.staging
        volumes:
            - ../app:/var/www/istsi:ro
            - data-app:/var/www/data
            - data-app-log:/var/www/logs
    composer:
        build: composer
        user: www-data
        command: install --no-dev -o
        volumes:
            - ../app:/var/www/istsi
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile.staging
        ports:
            - 443:443
        volumes:
            - ../app/public:/var/www/istsi/public:ro

volumes:
    data-mysql:
        driver: local
    data-app:
        driver: local
    data-app-log:
        driver: local