FROM php:7.1-fpm

RUN usermod -u 1000 www-data
RUN cd /var/www && mkdir -p cache && chown -R www-data:www-data cache

RUN apt-get update && apt-get install -y zlib1g-dev

RUN docker-php-ext-install pdo pdo_mysql zip opcache

COPY shared/php.ini /usr/local/etc/php/php.ini
COPY prod/php.ini /usr/local/etc/php/php.ini.prod
RUN cd /usr/local/etc/php && cat php.ini.prod >> php.ini

WORKDIR /var/www/istsi