FROM php:7.1-fpm

ARG env

RUN usermod -u 1000 www-data
RUN cd /var/www && mkdir -p cache data logs && chown -R www-data:www-data cache data logs

RUN apt-get update && apt-get install -y libpq-dev zlib1g-dev

RUN docker-php-ext-install pdo pdo_pgsql pdo_mysql zip opcache

COPY shared/php.ini /usr/local/etc/php/php.ini
COPY $env/php.ini /usr/local/etc/php/php.ini.$env
RUN cd /usr/local/etc/php && cat php.ini.$env >> php.ini

WORKDIR /var/www/istsi