FROM php:7.1-fpm

RUN usermod -u 1000 www-data
RUN cd /var/www && mkdir -p cache && chown -R www-data:www-data cache

RUN apt-get update && apt-get install -y zlib1g-dev

RUN docker-php-ext-install pdo pdo_mysql zip opcache

COPY shared/php.ini /usr/local/etc/php/php.ini
COPY dev/php.ini /usr/local/etc/php/php.ini.dev
RUN cd /usr/local/etc/php && cat php.ini.dev >> php.ini

RUN pecl install -o -f xdebug && docker-php-ext-enable xdebug
COPY dev/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

WORKDIR /var/www/istsi
